[project]
authors = [{ name = "Sen-wen Deng", email = "senwen.deng@l2it.in2p3.fr" }]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dependencies = [
  "numpy >= 1.26.0",
  "scipy >= 1.12.0",
  "h5py",
  "astropy",
  "array-api-compat >= 1.13.0",
  "mojito>=0.5.0",
]
description = "Fully typed interfaces for LISA data analysis"
dynamic = ["version"]
name = "typed-lisa-toolkit"
readme = "README.md"
requires-python = ">=3.13"

[project.optional-dependencies]
jax = ["jax; sys_platform != 'darwin' or platform_machine != 'x86_64'"]
torch = ["torch; sys_platform != 'darwin' or platform_machine != 'x86_64'"]
quadax = ["quadax; sys_platform != 'darwin' or platform_machine != 'x86_64'"]
wdm = ["wdm-transform>=0.2"]

[dependency-groups]
dev = [
  "ruff",
  "h5py-stubs>=0.1.2",
  "myst-nb>=1.3.0",
  "nb-clean>=4.0.1",
  "pre-commit>=4.5.1",
  "pylint>=4.0.4",
  "pytest>=9.0.2",
  "pytest-cov>=7.0.0",
  "pytest-mock>=3.15.1",
  "uv-dynamic-versioning>=0.12.0",
  { include-group = "quadax" },
  "basedpyright",
  "mojito-processor",
]
doc = [
  "sphinx",
  "sphinx-autodoc-typehints",
  "sphinx-copybutton",
  "sphinxcontrib-bibtex",
  "sphinxcontrib-mermaid",
  "sphinx-inline-tabs",
  "furo",
  "fastgb",
  "anybadge",
  "ipywidgets",
  "lovelyplots",
]
jax = ["jax; sys_platform != 'darwin' or platform_machine != 'x86_64'"]
quadax = [
  { include-group = "jax" },
  "quadax; sys_platform != 'darwin' or platform_machine != 'x86_64'",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.version]
source = "uv-dynamic-versioning"

[tool.hatch.build.targets.wheel]
packages = ["src/typed_lisa_toolkit"]

[tool.uv-dynamic-versioning]
enable = true
pattern = "default-unprefixed"
style = "semver"
vcs = "git"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling", "uv-dynamic-versioning"]

[tool.ruff.lint]
ignore = [
  "D104",
  "PLC0415",
  "PLR0913",
  "COM812",
  "SLF001",
  "TID252",
  "TC001",
  "TC002",
  "TC003",
  "TC004",
]
select = [
  "D",
  "PL",
  "F",
  "S",
  "FBT",
  "B",
  "COM",
  "DTZ",
  "T10",
  "ISC",
  "EM",
  "ICN",
  "LOG",
  "G",
  "INP",
  "PIE",
  "PYI",
  "PT",
  "Q",
  "RSE",
  "RET",
  "SIM",
  "SLOT",
  "TID",
  "TD",
  "TC",
  "ARG",
  "PTH",
  "FLY",
  "I",
  "C90",
  "NPY",
  "PD",
  "N",
  "PERF",
  "E",
  "W",
  "PGH",
  "UP",
  "FURB",
  "RUF",
  "TRY",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
"docs/**" = ["D", "PL", "DOC", "INP", "RET504", "C901", "N806", "PERF", "E402"]
"tests/**" = ["D", "PL", "DOC", "INP", "S101", "N802", "F821"]
"src/typed_lisa_toolkit/_l2d_interface/**" = ["ALL"]

[tool.coverage.report]
omit = [
  "*/typed_lisa_toolkit/containers/modes.py",
  "*/typed_lisa_toolkit/_viz/*",
  "*/typed_lisa_toolkit/_l2d_interface/*",
]

[tool.pytest]
markers = ["slow"]

[tool.hatch.build.targets.wheel.force-include]
"src/typed_lisa_toolkit/py.typed" = "typed_lisa_toolkit/py.typed"

[tool.basedpyright]
defineConstant = { DEBUG = true }
enableTypeIgnoreComments = true
exclude = ["**/__pycache__", "src/typed_lisa_toolkit/_l2d_interface/*"]
executionEnvironments = [
  { root = "tests", reportPrivateUsage = false },
  { root = "src" },
]
ignore = ["docs"]
include = ["src"]
reportAny = "none"
reportDeprecated = false
reportExplicitAny = "none"
reportIgnoreCommentWithoutRule = "none"
reportImplicitOverride = "none"
reportImportCycles = false
reportMissingImports = "error"
reportMissingTypeStubs = false
reportUnusedCallResult = "none"
