stages:
  - docs

variables:
  SPHINX_VERSION: "8.0.2"

pages:
  stage: docs
  image: ghcr.io/sphinx-doc/sphinx:$SPHINX_VERSION
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  script:
    - apt-get update
    - apt-get -y --no-install-recommends install git gcc libc-dev
    - pip install --root-user-action=ignore --upgrade pip
    - pip install --root-user-action=ignore -r docs/docs-requirements.txt
    - pip install --root-user-action=ignore .
    - cd docs
    - make clean html
    - cd ..
    - mv docs/_build/html public
  artifacts:
    paths:
      - public
