stages:
  - docs

variables:
  SPHINX_VERSION: "8.0.2"

pages:
  stage: docs
  image: ghcr.io/sphinx-doc/sphinx:$SPHINX_VERSION
  script:
    - apt-get update
    - apt-get -y --no-install-recommends install git gcc libc-dev
    - pip install --upgrade pip
    - pip install -r docs/docs-requirements.txt
    - pip install .
    - cd docs
    - make clean html
    - cd ..
    - mv docs/_build/html public
  artifacts:
    paths:
      - public
