"""Module for the noise model.

A noise model carries the knowledge of noise properties in the data.
It determines the geometry of the data space, of which the template
space is a subspace.

.. currentmodule:: typed_lisa_toolkit.containers.noisemodel

Types
-----

.. autoclass:: FSDataT
.. autoclass:: NPNumT
.. autoprotocol:: StationaryFDNoise
.. autoprotocol:: Integrator
.. autoprotocol:: CumIntegrator
.. autoclass:: IntegratorConfig

Entities
--------

.. autoclass:: FDNoiseModel
   :members:
   :member-order: groupwise
   :inherited-members:

"""

import abc
import logging
from typing import Protocol, TypeVar, TypedDict, Unpack, Self

import numpy as np
import numpy.typing as npt
import scipy.integrate  # type: ignore[import]

from . import arithdicts
from . import representations as reps
from . import data
from .. import utils

log = logging.getLogger(__name__)

ChnName = str
FSDataT = TypeVar("FSDataT", bound=data.FSData)
NPNumT = TypeVar("NPNumT", bound=np.number)


class Integrator(Protocol):
    """Protocol for integrators."""

    def __call__(
        self,
        __y: npt.NDArray[NPNumT],
        **kwargs,
    ) -> NPNumT:
        """Integrate the given data."""


class CumIntegrator(Protocol):
    """Protocol for cumulative integrators."""

    def __call__(
        self,
        __y: npt.NDArray[NPNumT],
        **kwargs,
    ) -> npt.NDArray[NPNumT]:
        """Integrate the given data cumulatively."""


class IntegratorConfig(TypedDict):
    """Dictionary for integrator and cumulative integrator configuration."""

    integrator: Integrator
    cumulative_integrator: CumIntegrator


def _collect_frequencies(data: data.FSData):
    return arithdicts.ChannelDict(
        {chnname: series.frequencies for chnname, series in data.items()}
    )


class StationaryFDNoise(Protocol):
    """Protocol for frequency domain stationary noise PSD models."""

    def psd(
        self, frequencies: npt.NDArray[np.floating], option: ChnName
    ) -> npt.NDArray[np.floating]:
        """Return the power spectral density (PSD)."""


class FDNoiseModel:
    """Frequency domain noise model.

    Assuming the noise is stationary, the noise model is given by the
    noise power spectral density (PSD) in the frequency domain. This
    class might not be suitable for non-stationary noise.

    """

    _DEFAULT_INTEGRATOR = scipy.integrate.trapezoid
    _DEFAULT_CUM_INTEGRATOR = scipy.integrate.cumulative_trapezoid

    def __init__(
        self,
        integrator: Integrator = _DEFAULT_INTEGRATOR,
        cumulative_integrator: CumIntegrator = _DEFAULT_CUM_INTEGRATOR,
    ) -> None:
        self.integrator = integrator
        self.cumulative_integrator = cumulative_integrator

    @abc.abstractmethod
    def create_new(
        self,
        integrator: Integrator = _DEFAULT_INTEGRATOR,
        cumulative_integrator: CumIntegrator = _DEFAULT_CUM_INTEGRATOR,
    ) -> Self:
        """Return a new instance of the class with the given integrators."""

    @classmethod
    def make(
        cls,
        fd_noise: StationaryFDNoise | None = None,
        noise_cache: data.FSData | None = None,
        **kwargs: Unpack[IntegratorConfig],
    ):
        """Return an :class:`.FDNoiseModel` instance.

        To create an instance, either provide a noise PSD model or a noise
        PSD cache. If both are provided, an error is raised.

        The user may also provide a custom integrator :class:`.Integrator`
        and/or a custom cumulative integrator :class:`.CumIntegrator` to be
        used in the scalar product and the cumulative scalar product
        computations. The default integrator is :func:`scipy.integrate.trapezoid`
        and the default cumulative integrator is :func:`scipy.integrate.cumulative_trapezoid`.
        """
        args = (fd_noise, noise_cache)
        error = ValueError(
            "Exactly one of fd_noise and noise_cache should be provided."
        )
        if sum(arg is not None for arg in args) != 1:
            raise error
        if fd_noise is not None:
            return _StationaryNoiseModel(fd_noise, **kwargs)
        if noise_cache is not None:
            return _CacheNoiseModel(noise_cache, **kwargs)
        raise error

    @abc.abstractmethod
    def get_noise_psd(
        self, frequencies: arithdicts.ChannelDict[npt.NDArray[data.NPFloatingT]]
    ) -> data.FSData:
        """Return the noise PSD.

        This method returns the noise PSD generated by the noise PSD model
        or stored in the cache, on the given dictionary of frequencies.
        """

    def get_integrand(
        self,
        left: data.FSData[
            data.NPFloatingT,
            data.NPNumberT,
        ],
        right: data.FSData[
            data.NPFloatingT,
            data.NPNumberT,
        ],
    ) -> data.FSData[data.NPFloatingT, data.NPNumberT]:
        r"""Return the integrand of the scalar product.

        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns

        .. math::

            4\frac{d(f) h^*(f)}{S_n(f)}.
        """
        noise_psd = self.get_noise_psd(_collect_frequencies(left))
        return 4 * left * (1 / noise_psd) * right.conj()

    def get_complex_scalar_product(
        self,
        left: data.FSData[
            data.NPFloatingT,
            np.complexfloating,
        ],
        right: data.FSData[
            data.NPFloatingT,
            np.complexfloating,
        ],
    ) -> arithdicts.ChannelDict[np.complexfloating]:
        r"""Return the complex scalar product.

        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns

        .. math::

            \langle d, h \rangle = 4 \int_{f_\text{min}}^{f_\text{max}} \frac{d(f) h^*(f)}{S_n(f)} \, \mathrm{d} f.
        """
        integrand = self.get_integrand(left, right)
        _dict = {
            chnname: self.integrator(series.entries, x=series.frequencies)
            for chnname, series in integrand.items()
        }
        return arithdicts.ChannelDict(_dict)

    def get_cumulative_complex_scalar_product(
        self,
        left: data.FSData[
            data.NPFloatingT,
            np.complexfloating,
        ],
        right: data.FSData[
            data.NPFloatingT,
            np.complexfloating,
        ],
    ):
        r"""Return the cumulative complex scalar product.

        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns an array of the following function on the input frequency grid
        :math:`[f_\text{min}, f_\text{max}]`:

        .. math::

            F \mapsto 4\int_{f_\text{min}}^{F} \frac{d(f) h^*(f)}{S_n(f)} \, \mathrm{d} f.
        """
        integrand = self.get_integrand(left, right)

        def make_product(
            chname: ChnName,
        ) -> npt.NDArray[np.complexfloating]:
            series = integrand[chname]

            return self.cumulative_integrator(
                series.entries, x=series.frequencies, initial=0
            )

        _dict = {chnname: make_product(chnname) for chnname in integrand.keys()}
        return arithdicts.ChannelDict(_dict)

    def get_scalar_product(
        self,
        left: data.FSData[
            data.NPFloatingT,
            np.complexfloating,
        ],
        right: data.FSData[
            data.NPFloatingT,
            np.complexfloating,
        ],
    ):
        r"""Return the scalar product.

        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns

        .. math::

            \left( d \middle| h \right) = 4 \Re \int_{f_\text{min}}^{f_\text{max}} \frac{d(f) h^*(f)}{S_n(f)} \, \mathrm{d} f.
        """
        return self.get_complex_scalar_product(left, right).pass_through(np.real)

    def get_cumulative_scalar_product(
        self,
        left: data.FSData[
            data.NPFloatingT,
            np.complexfloating,
        ],
        right: data.FSData[
            data.NPFloatingT,
            np.complexfloating,
        ],
    ):
        r"""Return the cumulative scalar product.

        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns an array of the following function on the input frequency grid
        :math:`[f_\text{min}, f_\text{max}]`:

        .. math::

            F \mapsto 4\Re \int_{f_\text{min}}^{F} \frac{d(f) h^*(f)}{S_n(f)} \, \mathrm{d} f.
        """
        return self.get_cumulative_complex_scalar_product(left, right).pass_through(
            np.real
        )

    def get_cross_correlation(
        self,
        left: data.TimedFSData[
            data.NPFloatingT,
            np.complexfloating,
        ],
        right: data.FSData[
            data.NPFloatingT,
            np.complexfloating,
        ],
    ) -> arithdicts.ChannelDict[reps.TimeSeries[np.floating, np.complex128]]:
        r"""Return the cross correlation.

        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        we define the cross-correlation as

        .. math::

            (d \ast h)(\tau) := \left( \hat{d}(t) \middle| \hat{h}(t + \tau) \right),

        where the hat denotes the real Fourier transform. This methods returns a generalization of the above
        cross-correlation which is **complex-valued**

        .. math::

            (d \star h)(\tau) := \langle \hat{d}(t), \hat{h}(t + \tau) \rangle.

        In the implementation, the generalized cross-correlation is computed using

        .. math::

            (d \star h)(\tau) \propto \mathcal{F}^{-1}\left(4\frac{d(f) h^*(f)}{S_n(f)}\right),

        where :math:`\mathcal{F}^{-1}` is the two-sided inverse Fourier transform. Note
        that the input arrays :math:`d(f)` and :math:`h(f)` are one-sided, and the negative frequencies are
        populated by **zero** before the inverse Fourier transform.
        """
        two_sided_freq = np.fft.fftshift(
            np.fft.fftfreq(len(left.times), left.times[1] - left.times[0])
        )
        integrand = self.get_integrand(left, right)
        inband_slice = utils.get_subset_slice(
            two_sided_freq, integrand.frequencies[0], integrand.frequencies[-1]
        )
        # Note that we assumed all the channels have the same frequency grid.

        def make_cross_correlation(chnname: ChnName):
            series = integrand[chnname]
            integrand_two_sided_freq = np.zeros_like(
                two_sided_freq, dtype=series.entries.dtype
            )
            integrand_two_sided_freq[inband_slice] = series.entries
            # Pay attention to the sign convention (ifft or fft) and the normalization.
            cross_correlation = np.fft.ifft(
                np.fft.ifftshift(integrand_two_sided_freq) * integrand.df,
                len(left.times),
                norm="forward",
            )
            return reps.TimeSeries(left.times, cross_correlation)

        _dict = {
            chnname: make_cross_correlation(chnname) for chnname in integrand.keys()
        }
        return arithdicts.ChannelDict(_dict)

    def get_whitened(self, data: FSDataT) -> FSDataT:
        r"""Return the whitened data.

        Assuming the noise PSD is :math:`S_n(f)`, this method returns

        .. math::

            \frac{d(f)}{\sqrt{S_n(f)}}.
        """
        noise_psd = self.get_noise_psd(_collect_frequencies(data))
        return data / noise_psd.sqrt()

    def get_overlap(self, left: data.FSData, right: data.FSData):
        r"""Return the overlap.

        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns

        .. math::

            \frac{\langle d, h \rangle}{\sqrt{\langle d, d \rangle \langle h, h \rangle}}.
        """
        left_norm_square = self.get_scalar_product(left, left)
        right_norm_square = self.get_scalar_product(right, right)
        overlap = self.get_scalar_product(left, right) / (
            left_norm_square * right_norm_square
        ).pass_through(np.sqrt)
        return overlap

    def get_cache(self, data: data.FSData):
        """Return the cache.

        This method returns an instance of :class:`.FDNoiseModel` that
        caches the noise PSD on the grid of the given data. The cache
        can then be used in the computation on the same grid or a
        subset of it, without calling the noise PSD model again.
        """
        noise_psd = self.get_noise_psd(_collect_frequencies(data))
        return _CacheNoiseModel(
            noise_cache=noise_psd,
            integrator=self.integrator,
            cumulative_integrator=self.cumulative_integrator,
        )


class _StationaryNoiseModel(FDNoiseModel):
    def __init__(
        self, fd_noise: StationaryFDNoise, **kwargs: Unpack[IntegratorConfig]
    ) -> None:
        super().__init__(**kwargs)
        self.fd_noise = fd_noise

    def create_new(
        self,
        integrator: Integrator = FDNoiseModel._DEFAULT_INTEGRATOR,
        cumulative_integrator: CumIntegrator = FDNoiseModel._DEFAULT_CUM_INTEGRATOR,
    ):
        return type(self)(
            self.fd_noise,
            integrator=integrator,
            cumulative_integrator=cumulative_integrator,
        )

    def get_noise_psd(
        self, frequencies: arithdicts.ChannelDict[npt.NDArray[data.NPFloatingT]]
    ):
        def make_psd(chnname: ChnName):
            freq = frequencies[chnname]
            entries = self.fd_noise.psd(freq, option=chnname)
            return reps.FrequencySeries(freq, entries)

        _dict = {chnname: make_psd(chnname) for chnname in frequencies.keys()}
        return data.FSData(_dict)


class _CacheNoiseModel(FDNoiseModel):
    def __init__(
        self, noise_cache: data.FSData, **kwargs: Unpack[IntegratorConfig]
    ) -> None:
        super().__init__(**kwargs)
        self.noise_cache = noise_cache

    def create_new(
        self,
        integrator: Integrator = FDNoiseModel._DEFAULT_INTEGRATOR,
        cumulative_integrator: CumIntegrator = FDNoiseModel._DEFAULT_CUM_INTEGRATOR,
    ):
        return type(self)(
            self.noise_cache,
            integrator=integrator,
            cumulative_integrator=cumulative_integrator,
        )

    def get_noise_psd(
        self, frequencies: arithdicts.ChannelDict[npt.NDArray[data.NPFloatingT]]
    ):
        freq = next(iter(frequencies.values()))
        try:
            interval = freq[0], freq[-1]
        except IndexError:
            interval = (0, 0)  # An empty interval.
        noise_psd = self.noise_cache.get_subset(interval=interval)
        if log.isEnabledFor(logging.DEBUG):
            try:
                assert np.array_equal(
                    noise_psd.frequencies, freq
                ), f"The frequencies {noise_psd.frequencies} and {freq} are not exactly equal."
            except AssertionError as e:
                log.debug(e)
                try:
                    assert np.allclose(
                        noise_psd.frequencies, freq
                    ), f"The frequencies {noise_psd.frequencies} and {freq} are not close."
                except AssertionError as exc:
                    log.debug(exc)
        return noise_psd
