"""Module for sensitivity.

Sensitivity carries the knowledge of noise properties in the data.
It determines the geometry of the data space, of which the template
space is a subspace.

.. currentmodule:: typed_lisa_toolkit.containers.sensitivity

Types
-----

.. autoprotocol:: FDNoiseModel

Entities
--------

.. autoclass:: FDSensitivity
   :members:
   :member-order: groupwise
   :inherited-members:

"""

import abc
import logging
from typing import Protocol, overload

import numpy as np
import numpy.typing as npt
import scipy.integrate  # type: ignore

from . import arithdicts
from . import representations as reps
from . import data as data_
from .. import utils

log = logging.getLogger(__name__)

ChnName = str


def _collect_frequencies(data: data_.FSData):
    return arithdicts.ChannelDict(
        {chnname: series.frequencies for chnname, series in data.items()}
    )


class FDNoiseModel(Protocol):
    """Protocol for frequency domain noise models."""

    def psd(
        self, frequencies: npt.NDArray[np.floating], option: ChnName
    ) -> npt.NDArray[np.floating]:
        """Return the power spectral density (PSD)."""


class Sensitivity:
    """Base sensitivity class."""


class FDSensitivity(Sensitivity):
    """Frequency domain sensitivity.

    Assuming the noise is stationary, the sensitivity is given by the
    noise power spectral density (PSD) in the frequency domain. This
    class might not be suitable for non-stationary noise.

    """

    def __init__(
        self,
        integrator=scipy.integrate.trapezoid,
        cumulative_integrator=scipy.integrate.cumulative_trapezoid,
    ) -> None:
        self.integrator = integrator
        self.cumulative_integrator = cumulative_integrator

    def create_new(self, integrator, cumulative_integrator):
        """Return a new instance of the class with the given integrators."""
        return type(self)(integrator, cumulative_integrator)

    @classmethod
    def make(
        cls,
        noise_model: FDNoiseModel | None = None,
        noise_cache: data_.FSData | None = None,
    ):
        """Return an :class:`.FDSensitivity` instance.

        To create an instance, either provide a noise model or a noise
        PSD cache. If both are provided, an error is raised.
        """
        args = (noise_model, noise_cache)
        error = ValueError(
            "Exactly one of noise_model and noise_cache should be provided."
        )
        if sum(arg is not None for arg in args) != 1:
            raise error
        if noise_model is not None:
            return _NoiseModelSensitivity(noise_model)
        if noise_cache is not None:
            return _CacheSensitivity(noise_cache)
        raise error

    @abc.abstractmethod
    def get_noise_psd(
        self, frequencies: arithdicts.ChannelDict[npt.NDArray[data_.NPFloatingT]]
    ) -> data_.FSData:
        """Return the noise PSD.

        This method returns the noise PSD generated by the noise model
        or stored in the cache, on the given dictionary of frequencies.
        """

    def get_integrand(
        self,
        left: data_.FSData[
            data_.NPFloatingT,
            data_.NPNumberT,
        ],
        right: data_.FSData[
            data_.NPFloatingT,
            data_.NPNumberT,
        ],
    ) -> data_.FSData[data_.NPFloatingT, data_.NPNumberT]:
        r"""Return the integrand of the scalar product.

        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns

        .. math::

            4\frac{d(f) h^*(f)}{S_n(f)}.
        """
        noise_psd = self.get_noise_psd(_collect_frequencies(left))
        return 4 * left * (1 / noise_psd) * right.conj()

    def get_complex_scalar_product(
        self,
        left: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
        right: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
    ) -> arithdicts.ChannelDict[np.complexfloating]:
        r"""Return the complex scalar product.

        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns

        .. math::

            \langle d, h \rangle = 4 \int_{f_\text{min}}^{f_\text{max}} \frac{d(f) h^*(f)}{S_n(f)} \, \mathrm{d} f.
        """
        integrand = self.get_integrand(left, right)
        _dict = {
            chnname: self.integrator(series.entries, x=series.frequencies)
            for chnname, series in integrand.items()
        }
        return arithdicts.ChannelDict(_dict)  # type: ignore
        # Either I misleaded the type hint of np.trapezoid or it was wrong.
        # It doesn't seem to create any problem in practice. To check later.

    def get_cumulative_complex_scalar_product(
        self,
        left: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
        right: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
    ):
        r"""Return the cumulative complex scalar product.

        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns an array of the following function on the input frequency grid
        :math:`[f_\text{min}, f_\text{max}]`:

        .. math::

            F \mapsto 4\int_{f_\text{min}}^{F} \frac{d(f) h^*(f)}{S_n(f)} \, \mathrm{d} f.
        """
        integrand = self.get_integrand(left, right)

        def make_product(
            chname: ChnName,
        ) -> npt.NDArray[np.complexfloating]:
            series = integrand[chname]

            return self.cumulative_integrator(
                series.entries, x=series.frequencies, initial=0
            )

        _dict = {chnname: make_product(chnname) for chnname in integrand.keys()}
        return arithdicts.ChannelDict(_dict)

    def get_scalar_product(
        self,
        left: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
        right: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
    ):
        r"""Return the scalar product.

        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns

        .. math::

            \left( d \middle| h \right) = 4 \Re \int_{f_\text{min}}^{f_\text{max}} \frac{d(f) h^*(f)}{S_n(f)} \, \mathrm{d} f.
        """
        return self.get_complex_scalar_product(left, right).pass_through(np.real)

    def get_cumulative_scalar_product(
        self,
        left: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
        right: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
    ):
        r"""Return the cumulative scalar product.

        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns an array of the following function on the input frequency grid
        :math:`[f_\text{min}, f_\text{max}]`:

        .. math::

            F \mapsto 4\Re \int_{f_\text{min}}^{F} \frac{d(f) h^*(f)}{S_n(f)} \, \mathrm{d} f.
        """
        return self.get_cumulative_complex_scalar_product(left, right).pass_through(
            np.real
        )

    def get_cross_correlation(
        self,
        left: data_.TimedFSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
        right: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
    ) -> arithdicts.ChannelDict[reps.TimeSeries[np.floating, np.complex128]]:
        r"""Return the cross correlation.

        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        we define the cross-correlation as

        .. math::

            (d \ast h)(\tau) := \left( \hat{d}(t) \middle| \hat{h}(t + \tau) \right),

        where the hat denotes the real Fourier transform. This methods returns a generalization of the above
        cross-correlation which is **complex-valued**

        .. math::

            (d \star h)(\tau) := \langle \hat{d}(t), \hat{h}(t + \tau) \rangle.

        In the implementation, the generalized cross-correlation is computed using

        .. math::

            (d \star h)(\tau) \propto \mathcal{F}^{-1}\left(4\frac{d(f) h^*(f)}{S_n(f)}\right),

        where :math:`\mathcal{F}^{-1}` is the two-sided inverse Fourier transform. Note
        that the input arrays :math:`d(f)` and :math:`h(f)` are one-sided, and the negative frequencies are
        populated by **zero** before the inverse Fourier transform.
        """
        two_sided_freq = np.fft.fftshift(
            np.fft.fftfreq(len(left.times), left.times[1] - left.times[0])
        )
        integrand = self.get_integrand(left, right)
        inband_slice = utils.get_subset_slice(
            two_sided_freq, integrand.frequencies[0], integrand.frequencies[-1]
        )
        # Note that we assumed all the channels have the same frequency grid.

        def make_cross_correlation(chnname: ChnName):
            series = integrand[chnname]
            integrand_two_sided_freq = np.zeros_like(
                two_sided_freq, dtype=series.entries.dtype
            )
            integrand_two_sided_freq[inband_slice] = series.entries
            # Pay attention to the sign convention (ifft or fft) and the normalization.
            cross_correlation = np.fft.ifft(
                np.fft.ifftshift(integrand_two_sided_freq) * integrand.df,
                len(left.times),
                norm="forward",
            )
            return reps.TimeSeries(left.times, cross_correlation)

        _dict = {
            chnname: make_cross_correlation(chnname) for chnname in integrand.keys()
        }
        return arithdicts.ChannelDict(_dict)

    @overload
    def get_whitened(self, data: data_.TimedFSData) -> data_.TimedFSData: ...

    @overload
    def get_whitened(self, data: data_.FSData) -> data_.FSData: ...

    def get_whitened(self, data: data_.FSData):
        r"""Return the whitened data.

        Assuming the noise PSD is :math:`S_n(f)`, this method returns

        .. math::

            \frac{d(f)}{\sqrt{S_n(f)}}.
        """
        noise_psd = self.get_noise_psd(_collect_frequencies(data))
        return data / noise_psd.sqrt()

    def get_overlap(self, left: data_.FSData, right: data_.FSData):
        r"""Return the overlap.

        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns

        .. math::

            \frac{\langle d, h \rangle}{\sqrt{\langle d, d \rangle \langle h, h \rangle}}.
        """
        left_norm_square = self.get_scalar_product(left, left)
        right_norm_square = self.get_scalar_product(right, right)
        overlap = self.get_scalar_product(left, right) / (
            left_norm_square * right_norm_square
        ).pass_through(np.sqrt)
        return overlap

    def get_cache(self, data: data_.FSData):
        """Return the cache.

        This method returns an instance of :class:`.FDSensitivity` that
        caches the noise PSD on the grid of the given data. The cache
        can then be used in the computation on the same grid or a
        subset of it, without calling the noise model again.
        """
        noise_psd = self.get_noise_psd(_collect_frequencies(data))
        return _CacheSensitivity(
            noise_cache=noise_psd,
            integrator=self.integrator,
            cumulative_integrator=self.cumulative_integrator,
        )


class _NoiseModelSensitivity(FDSensitivity):
    def __init__(self, noise_model: FDNoiseModel, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.noise_model = noise_model

    def create_new(self, integrator, cumulative_integrator):
        return type(self)(self.noise_model, integrator, cumulative_integrator)

    def get_noise_psd(
        self, frequencies: arithdicts.ChannelDict[npt.NDArray[data_.NPFloatingT]]
    ):
        def make_psd(chnname: ChnName):
            freq = frequencies[chnname]
            entries = self.noise_model.psd(freq, option=chnname)
            return reps.FrequencySeries(freq, entries)

        _dict = {chnname: make_psd(chnname) for chnname in frequencies.keys()}
        return data_.FSData(_dict)


class _CacheSensitivity(FDSensitivity):
    def __init__(self, noise_cache: data_.FSData, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)
        self.noise_cache = noise_cache

    def create_new(self, integrator, cumulative_integrator):
        return type(self)(self.noise_cache, integrator, cumulative_integrator)

    def get_noise_psd(
        self, frequencies: arithdicts.ChannelDict[npt.NDArray[data_.NPFloatingT]]
    ):
        freq = next(iter(frequencies.values()))
        try:
            interval = freq[0], freq[-1]
        except IndexError:
            interval = (0, 0) # An empty interval.
        noise_psd = self.noise_cache.get_subset(interval=interval)
        if log.isEnabledFor(logging.DEBUG):
            try:
                assert np.array_equal(
                    noise_psd.frequencies, freq
                ), f"The frequencies {noise_psd.frequencies} and {freq} are not exactly equal."
            except AssertionError as e:
                log.debug(e)
                try:
                    assert np.allclose(
                        noise_psd.frequencies, freq
                    ), f"The frequencies {noise_psd.frequencies} and {freq} are not close."
                except AssertionError as exc:
                    log.debug(exc)
        return noise_psd
