"""Module for sensitivity.

Sensitivity carries the knowledge of noise properties in the data.
It determines the geometry of the data space, of which the template
space is a subspace.

.. currentmodule:: typed_lisa_toolkit.containers.sensitivity

Entities
--------

.. autoprotocol:: FDNoiseModel

.. autoclass:: FDSensitivity
   :members:
   :member-order: groupwise
   :inherited-members:

"""

import abc
from typing import Protocol

import numpy as np
import numpy.typing as npt

from . import arithdicts
from . import representations as repr
from . import data as data_
from .. import utils

ChnName = str


class FDNoiseModel(Protocol):
    """Protocol for frequency domain noise models."""

    @abc.abstractmethod
    def psd(self, *args, option: ChnName, **kwargs) -> npt.NDArray[np.floating]:
        """Return the PSD."""


class Sensitivity:
    """Base sensitivity class."""


class FDSensitivity(Sensitivity):
    """Frequency domain sensitivity.

    Assuming the noise is stationary, the sensitivity is given by the
    noise power spectral density (PSD) in the frequency domain. This
    class might not be suitable for non-stationary noise.

    """

    @classmethod
    def make(
        cls,
        noise_model: FDNoiseModel | None = None,
        noise_cache: data_.FSData | None = None,
    ):
        """Return an :class:`.FDSensitivity` instance.

        To create an instance, either provide a noise model or a noise
        PSD cache. Only exactly one of them should be provided.
        """
        args = (noise_model, noise_cache)
        if sum(arg is not None for arg in args) != 1:
            raise ValueError(
                "Exactly one of noise_model and noise_cache should be provided."
            )
        if noise_model is not None:
            return _NoiseModelSensitivity(noise_model)
        elif noise_cache is not None:
            return _CacheSensitivity(noise_cache)

    @abc.abstractmethod
    def get_noise_psd(self, data: data_.FSData) -> data_.FSData:
        """Return the noise PSD.

        This method returns the noise PSD generated by the noise model
        or stored in the cache, on the same frequency grid and channels
        as the input data.
        """

    def get_integrand(
        self,
        left: data_.FSData[
            data_.NPFloatingT,
            data_.NPNumberT,
        ],
        right: data_.FSData[
            data_.NPFloatingT,
            data_.NPNumberT,
        ],
    ) -> data_.FSData[data_.NPFloatingT, data_.NPNumberT]:
        r"""Return the integrand of the scalar product.

        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns

        .. math::

            4\frac{d(f) h^*(f)}{S_n(f)}.
        """
        noise_psd = self.get_noise_psd(left)
        return 4.0 * (1.0 / noise_psd) * left * right.conj()

    def get_complex_scalar_product(
        self,
        left: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
        right: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
    ) -> arithdicts.ChannelDict[np.complexfloating]:
        r"""Return the complex scalar product.
        
        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns

        .. math::

            4 \int_{f_\text{min}}^{f_\text{max}} \frac{d(f) h^*(f)}{S_n(f)} \, \mathrm{d} f.
        """
        integrand = self.get_integrand(left, right)
        _dict = {
            chnname: np.trapezoid(series.entries, x=series.frequencies)
            for chnname, series in integrand.items()
        }
        return arithdicts.ChannelDict(_dict)  # type: ignore
        # Either I misleaded the type hint of np.trapezoid or it was wrong.
        # It doesn't seem to create any problem in practice. To check later.

    def get_cumulative_complex_scalar_product(
        self,
        left: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
        right: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
    ):
        r"""Return the cumulative complex scalar product.
        
        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns an array of the following function on the input frequency grid
        :math:`[f_\text{min}, f_\text{max}]`:

        .. math::

            F \mapsto 4\int_{f_\text{min}}^{F} \frac{d(f) h^*(f)}{S_n(f)} \, \mathrm{d} f.
        """
        integrand = self.get_integrand(left, right)

        def make_product(
            chname: ChnName,
        ) -> npt.NDArray[np.complexfloating]:
            series = integrand[chname]

            try:
                import scipy.integrate  # type: ignore
                # scipy stubs issue
            except ImportError:
                raise ImportError(
                    "scipy is required for cumulative trapezoidal integration."
                )

            return scipy.integrate.cumulative_trapezoid(
                series.entries, x=series.frequencies, initial=0
            )

        _dict = {chnname: make_product(chnname) for chnname in integrand.keys()}
        return arithdicts.ChannelDict(_dict)

    def get_scalar_product(
        self,
        left: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
        right: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
    ):
        r"""Return the scalar product.
        
        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns

        .. math::

            \langle d, h \rangle = 4 \Re \int_{f_\text{min}}^{f_\text{max}} \frac{d(f) h^*(f)}{S_n(f)} \, \mathrm{d} f.
        """
        return self.get_complex_scalar_product(left, right).pass_through(np.real)

    def get_cumulative_scalar_product(
        self,
        left: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
        right: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
    ):
        r"""Return the cumulative scalar product.
        
        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns an array of the following function on the input frequency grid
        :math:`[f_\text{min}, f_\text{max}]`:

        .. math::

            F \mapsto 4\Re \int_{f_\text{min}}^{F} \frac{d(f) h^*(f)}{S_n(f)} \, \mathrm{d} f.
        """
        return self.get_cumulative_complex_scalar_product(left, right).pass_through(
            np.real
        )

    def get_cross_correlation(
        self,
        left: data_.TimedFSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
        right: data_.FSData[
            data_.NPFloatingT,
            np.complexfloating,
        ],
    ) -> data_.TSData[np.floating, np.float64]:
        r"""Return the cross_correlation.
        
        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method computes the cross-correlation

        .. math::

            (d \ast h)(\tau) = \langle \hat{d}(t), \hat{h}(t + \tau) \rangle.

        In the implementation, the above expression is computed using

        .. math::

            (d \ast h)(\tau) \propto \mathcal{F}^{-1}\left(4\frac{d(f) h^*(f)}{S_n(f)}\right),

        where the hat denotes the real Fourier transform, :math:`\mathcal{F}^{-1}` the two-sided inverse Fourier transform. Note 
        that the input arrays :math:`d(f)` and :math:`h(f)` are one-sided, and the negative frequencies are populated by **zero**
        before the inverse Fourier transform.
        """
        two_sided_freq = np.fft.fftshift(
            np.fft.fftfreq(len(left.times), left.times[1] - left.times[0])
        )
        integrand = self.get_integrand(left, right)
        inband_slice = utils.get_subset_slice(
            two_sided_freq, integrand.frequencies[0], integrand.frequencies[-1]
        )
        # Note that we assumed all the channels have the same frequency grid.

        def make_cross_correlation(chnname: ChnName):
            series = integrand[chnname]
            integrand_two_sided_freq = np.zeros_like(
                two_sided_freq, dtype=series.entries.dtype
            )
            integrand_two_sided_freq[inband_slice] = series.entries
            # Pay attention to the sign convention (ifft or fft) and the normalization.
            cross_correlation = np.fft.ifft(
                np.fft.ifftshift(integrand_two_sided_freq) * integrand.df,
                len(left.times),
                norm="forward",
            )
            return repr.TimeSeries(left.times, cross_correlation.real)

        _dict = {chnname: make_cross_correlation(chnname) for chnname in integrand.keys()}
        return data_.TSData(_dict)

    def get_whitened(self, data: data_.FSData):
        r"""Return the whitened data.
        
        Assuming the noise PSD is :math:`S_n(f)`, this method returns

        .. math::

            \frac{d(f)}{\sqrt{S_n(f)}}.
        """
        noise_psd = self.get_noise_psd(data)
        return data / noise_psd.sqrt()

    def get_overlap(self, left: data_.FSData, right: data_.FSData):
        r"""Return the overlap.
        
        Assuming `left` is :math:`d`, `right` is :math:`h`, and the noise PSD is :math:`S_n(f)`,
        this method returns

        .. math::

            \frac{\langle d, h \rangle}{\sqrt{\langle d, d \rangle \langle h, h \rangle}}.
        """
        left_norm_square = self.get_scalar_product(left, left)
        right_norm_square = self.get_scalar_product(right, right)
        overlap = self.get_scalar_product(left, right) / (
            left_norm_square * right_norm_square
        ).pass_through(np.sqrt)
        return overlap

    def get_cache(self, data: data_.FSData):
        """Return the cache.

        This method returns an instance of :class:`.FDSensitivity` that
        caches the noise PSD on the grid of the given data. The cache
        can then be used in the computation on the same grid or a
        subset of it, without calling the noise model again.
        """
        noise_psd = self.get_noise_psd(data)
        return _CacheSensitivity(noise_cache=noise_psd)


class _NoiseModelSensitivity(FDSensitivity):
    def __init__(self, noise_model: FDNoiseModel) -> None:
        self.noise_model = noise_model

    def get_noise_psd(self, data: data_.FSData[data_.NPFloatingT, data_.NPNumberT]):
        def make_psd(chnname: ChnName):
            series = data[chnname]
            entries = self.noise_model.psd(series.frequencies, option=chnname)
            return repr.FrequencySeries(series.frequencies, entries)

        _dict = {chnname: make_psd(chnname) for chnname in data.keys()}
        return data_.FSData(_dict)


class _CacheSensitivity(FDSensitivity):
    def __init__(self, noise_cache: data_.FSData) -> None:
        self.noise_cache = noise_cache

    def get_noise_psd(self, data: data_.FSData[data_.NPFloatingT, data_.NPNumberT]):
        interval = data.frequencies[0], data.frequencies[-1]
        noise_psd = self.noise_cache.get_subset(interval=interval)
        assert np.array_equal(noise_psd.frequencies, data.frequencies)
        return noise_psd
