from typing import Any, Self
import numpy as np

class NDArrayMixin(np.lib.mixins.NDArrayOperatorsMixin):  # type: ignore[misc]
    def __add__(self, other: object) -> Self: ...
    def __radd__(self, other: object) -> Self: ...
    def __iadd__(self, other: object) -> Self: ...
    def __sub__(self, other: object) -> Self: ...
    def __rsub__(self, other: object) -> Self: ...
    def __isub__(self, other: object) -> Self: ...
    def __mul__(self, other: object) -> Self: ...
    def __rmul__(self, other: object) -> Self: ...
    def __imul__(self, other: object) -> Self: ...
    def __truediv__(self, other: object) -> Self: ...
    def __rtruediv__(self, other: object) -> Self: ...
    def __itruediv__(self, other: object) -> Self: ...
    def __pow__(self, other: object) -> Self: ...
    def __rpow__(self, other: object) -> Self: ...
    def __ipow__(self, other: object) -> Self: ...
    def __neg__(self) -> Self: ...
    def __pos__(self) -> Self: ...
    def __abs__(self) -> Self: ...
    def __invert__(self) -> Self: ...
    def __lt__(self, other: object) -> Self: ...
    def __le__(self, other: object) -> Self: ...
    def __eq__(self, other: object) -> Any: ...
    def __ne__(self, other: object) -> Any: ...
    def __gt__(self, other: object) -> Self: ...
    def __ge__(self, other: object) -> Self: ...
    def square(self, **kwargs) -> Self: ...
    def exp(self, **kwargs) -> Self: ...
    def sqrt(self, **kwargs) -> Self: ...
    def conj(self, **kwargs) -> Self: ...
    def abs(self, **kwargs) -> Self: ...
